<?php

/*
|--------------------------------------------------------------------------
| Finance / Accounts — Value catalogue
|--------------------------------------------------------------------------
| Single source of truth for the money-side enumerations:
|
|   - payment methods      (cash, bank, mobile banking, …)
|   - income categories    (income not tied to a sale)
|   - party types          (generic ledger counterparties)
|   - purchase item types  (feed, fingerlings, equipment, other)
|   - invoice prefixes     (sale / purchase reference generation)
|
| Consumed by:
|   - App\Http\Requests\Finance\*Request        (Rule::in)
|   - App\Http\Requests\Customer\*Request
|   - App\Http\Requests\Supplier\*Request
|   - App\Http\Requests\Party\*Request
|   - App\Services\Finance\*
|   - resources/views/**
|
| See docs/BUSINESS_LOGIC.md §3–§6 and docs/DATABASE.md §5.
*/

return [

    /*
    |--------------------------------------------------------------------------
    | Payment methods
    |--------------------------------------------------------------------------
    | Used by customer_payments.method and supplier_payments.method.
    */
    'payment_methods' => [
        'cash' => ['label' => 'Cash'],
        'bank' => ['label' => 'Bank transfer'],
        'bkash' => ['label' => 'bKash'],
        'nagad' => ['label' => 'Nagad'],
        'rocket' => ['label' => 'Rocket'],
        'cheque' => ['label' => 'Cheque'],
        'other' => ['label' => 'Other'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Income categories
    |--------------------------------------------------------------------------
    | Income that is NOT a fish sale. A fish sale posts to the Sales module and
    | attributes its money to a pond automatically.
    */
    'income_categories' => [
        'subsidy' => 'Subsidy / grant',
        'misc_sale' => 'Miscellaneous sale',
        'rent' => 'Rent received',
        'service' => 'Service income',
        'refund' => 'Refund received',
        'other' => 'Other income',
    ],

    /*
    |--------------------------------------------------------------------------
    | Party types
    |--------------------------------------------------------------------------
    | Generic ledger counterparties that are neither customers nor suppliers.
    */
    'party_types' => [
        'landlord' => ['label' => 'Landlord'],
        'agent' => ['label' => 'Agent / broker'],
        'worker' => ['label' => 'Worker / labour'],
        'transporter' => ['label' => 'Transporter'],
        'government' => ['label' => 'Government office'],
        'other' => ['label' => 'Other'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Purchase item types
    |--------------------------------------------------------------------------
    | Which kind of thing was bought on a purchase line.
    */
    'purchase_item_types' => [
        'feed' => 'Feed',
        'fingerlings' => 'Fish / fingerlings',
        'equipment' => 'Equipment',
        'medicine' => 'Medicine',
        'other' => 'Other',
    ],

    /*
    |--------------------------------------------------------------------------
    | Invoice / reference prefixes
    |--------------------------------------------------------------------------
    | Sequential references are generated by the services:
    |   sale     → SAL-2026-0001
    |   purchase → PUR-2026-0001
    */
    'invoice_prefixes' => [
        'sale' => 'SAL',
        'purchase' => 'PUR',
    ],

    /*
    |--------------------------------------------------------------------------
    | Sale / purchase statuses
    |--------------------------------------------------------------------------
    | Derived from (total − paid), never chosen by hand:
    |   paid    nothing outstanding
    |   partial something paid, something due
    |   due     nothing paid yet
    */
    'settlement_statuses' => [
        'paid' => ['label' => 'Paid', 'tone' => 'success'],
        'partial' => ['label' => 'Partial', 'tone' => 'warning'],
        'due' => ['label' => 'Due', 'tone' => 'danger'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Feeding — meal schedule recurrences and feeding statuses
    |--------------------------------------------------------------------------
    | once  = a single dated plan
    | daily = repeats every day at the scheduled time
    */
    'feed_schedule_recurrences' => [
        'once' => ['label' => 'One-off'],
        'daily' => ['label' => 'Daily'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Feeding statuses
    |--------------------------------------------------------------------------
    | Recorded when a feeding is actually performed:
    |   completed the planned amount was given
    |   partial   less was given than planned
    |   skipped   nothing was given (recorded for completeness, consumes no stock)
    */
    'feeding_statuses' => [
        'completed' => ['label' => 'Completed', 'tone' => 'success'],
        'partial' => ['label' => 'Partial', 'tone' => 'warning'],
        'skipped' => ['label' => 'Skipped', 'tone' => 'default'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Fish batch / cycle statuses
    |--------------------------------------------------------------------------
    | A batch is a stocking cycle for one pond + species. Its CURRENT quantity is
    | always derived from the movements tagged to it — never stored.
    */
    'batch_statuses' => [
        'active' => ['label' => 'Active', 'tone' => 'success'],
        'completed' => ['label' => 'Completed', 'tone' => 'info'],
        'harvested' => ['label' => 'Harvested', 'tone' => 'warning'],
        'cancelled' => ['label' => 'Cancelled', 'tone' => 'default'],
    ],
];
